require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::TextPagesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::TextPage. As you add validations to Admin::TextPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "page_type" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::TextPagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_text_pages as @admin_text_pages" do
      text_page = Admin::TextPage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_text_pages).should eq([text_page])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_text_page as @admin_text_page" do
      text_page = Admin::TextPage.create! valid_attributes
      get :show, {:id => text_page.to_param}, valid_session
      assigns(:admin_text_page).should eq(text_page)
    end
  end

  describe "GET new" do
    it "assigns a new admin_text_page as @admin_text_page" do
      get :new, {}, valid_session
      assigns(:admin_text_page).should be_a_new(Admin::TextPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_text_page as @admin_text_page" do
      text_page = Admin::TextPage.create! valid_attributes
      get :edit, {:id => text_page.to_param}, valid_session
      assigns(:admin_text_page).should eq(text_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::TextPage" do
        expect {
          post :create, {:admin_text_page => valid_attributes}, valid_session
        }.to change(Admin::TextPage, :count).by(1)
      end

      it "assigns a newly created admin_text_page as @admin_text_page" do
        post :create, {:admin_text_page => valid_attributes}, valid_session
        assigns(:admin_text_page).should be_a(Admin::TextPage)
        assigns(:admin_text_page).should be_persisted
      end

      it "redirects to the created admin_text_page" do
        post :create, {:admin_text_page => valid_attributes}, valid_session
        response.should redirect_to(Admin::TextPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_text_page as @admin_text_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::TextPage.any_instance.stub(:save).and_return(false)
        post :create, {:admin_text_page => { "page_type" => "invalid value" }}, valid_session
        assigns(:admin_text_page).should be_a_new(Admin::TextPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::TextPage.any_instance.stub(:save).and_return(false)
        post :create, {:admin_text_page => { "page_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_text_page" do
        text_page = Admin::TextPage.create! valid_attributes
        # Assuming there are no other admin_text_pages in the database, this
        # specifies that the Admin::TextPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::TextPage.any_instance.should_receive(:update_attributes).with({ "page_type" => "1" })
        put :update, {:id => text_page.to_param, :admin_text_page => { "page_type" => "1" }}, valid_session
      end

      it "assigns the requested admin_text_page as @admin_text_page" do
        text_page = Admin::TextPage.create! valid_attributes
        put :update, {:id => text_page.to_param, :admin_text_page => valid_attributes}, valid_session
        assigns(:admin_text_page).should eq(text_page)
      end

      it "redirects to the admin_text_page" do
        text_page = Admin::TextPage.create! valid_attributes
        put :update, {:id => text_page.to_param, :admin_text_page => valid_attributes}, valid_session
        response.should redirect_to(text_page)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_text_page as @admin_text_page" do
        text_page = Admin::TextPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::TextPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => text_page.to_param, :admin_text_page => { "page_type" => "invalid value" }}, valid_session
        assigns(:admin_text_page).should eq(text_page)
      end

      it "re-renders the 'edit' template" do
        text_page = Admin::TextPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::TextPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => text_page.to_param, :admin_text_page => { "page_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_text_page" do
      text_page = Admin::TextPage.create! valid_attributes
      expect {
        delete :destroy, {:id => text_page.to_param}, valid_session
      }.to change(Admin::TextPage, :count).by(-1)
    end

    it "redirects to the admin_text_pages list" do
      text_page = Admin::TextPage.create! valid_attributes
      delete :destroy, {:id => text_page.to_param}, valid_session
      response.should redirect_to(admin_text_pages_url)
    end
  end

end
