# settings.yml
# ========================
# This file is used to setup an application wide hash that can
# easily enable or disable specific feature sets. Any settings declared
# in this YAML file should be directly available in the ApplicationSettings class.




development:
  email_notifications: false

test:
  email_notifications: true

production:
  email_notifications: true