# settings.yml
# ========================
# This file is used to setup an application wide hash that can
# easily enable or disable specific feature sets. Any settings declared
# in this YAML file should be directly available in the ApplicationSettings class.




development:
  email_notifications: false
  site_url: 'http://localhost:3000/'
  smtp_user: 'yossish73'
  smtp_password: 'a1a2a3'

test:
  email_notifications: true
  site_url: 'http://localhost:3000/'
  smtp_user: 'yossish73'
  smtp_password: 'a1a2a3'

production:
  email_notifications: true
  site_url: 'http://feedfiction.com/'
  smtp_user: 'yossish73'
  smtp_password: 'a1a2a3'